version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: cms-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - cms-network
    restart: always

  backend:
    image: ${DOCKER_IMAGE_BACKEND:-liu-site-cms-backend}
    build: ./backend
    container_name: cms-backend
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    # 挂载 .env 文件，如果 backend 目录下有 .env 则使用，否则请手动创建
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    networks:
      - cms-network
    restart: always
    # volumes:
      # 移除单个文件的挂载，避免 Docker 自动将其创建为目录
      # - ./backend/backend.log:/app/backend.log

  redis:
    image: redis:alpine
    container_name: cms-redis
    networks:
      - cms-network
    restart: always
    volumes:
      - redis-data:/data

networks:
  cms-network:
    driver: bridge

volumes:
  redis-data:
